server:
  port: 8080
  servlet:
    encoding:  # 大模型对话中文乱码 UTF8编码出来
      enabled: true
      force: true
      charset: UTF-8

spring:
  application:
    name: SAA-12-RAG4AiOps
  ai:
    dashscope:  # SpringAIAlibaba Config
      api-key: ${ALI_API_KEY} # 从环境变量读取阿里云API Key（启动时需要在 idea中配置环境变量ALI_API_KEY=xxx）
      chat:  # 大模型对话配置
        options:
          model: deepseek-r1
      embedding:  # 大模型文本向量配置
        options:
          model: text-embedding-v3
    vectorstore:  # 向量数据库配置
      redis:
        initialize-schema: true
        index-name: custom-embed-index  # Redis 向量索引名称
        prefix: custom-embed-prefix  # Redis 向量数据前缀
  data:
    redis:  # Redis Config
      host: localhost
      port: 6379