server:
  port: 8080
  servlet:
    encoding:  # 大模型对话中文乱码 UTF8编码出来
      enabled: true
      force: true
      charset: UTF-8

spring:
  application:
    name: SAA-03-ChatModelChatClient
  ai:
    dashscope:  # SpringAIAlibaba Config
      api-key: ${ALI_API_KEY} # 从环境变量读取阿里云API Key（启动时需要在 idea中配置环境变量ALI_API_KEY=xxx）
      base-url: https://dashscope.aliyuncs.com/compatible-model/v1
      chat:
        options:
          model: qwen-plus  # 使用的模型名称，比如 qwen-plus、deepseek-v3 等

